### PR TITLE
failsafe for install.sh

### PR DESCRIPTION
**Pull request by Batwam**
fail-safe against being executed outside the repo directory...

### CODE REVIEW

**Comment by Moon-0xff** [comment]
I believe you can "reload" gnome-shell on wayland by quitting the session `$ gnome-session-quit`

**Comment by Batwam** [comment]
yeah, `$ gnome-session-quit` logs you out (technically asks you if you want to log out). I wouldn't include the command from the code as I think that most people probably would probably want to close whatever they have open first.but I could make the text more personalised based on `$XDG_SESSION_TYPE`

**Comment by Batwam** [comment]
Please run it on your end just in case but it's good to go as far as I'm concerned.

**Comment by Moon-0xff** [comment]
I've tested it.
The only *slight* issue i have so far is:
**If you execute it from outside the directory. It cd's you to the repository.**
I have pushed a "fix" for this. Let me know what you think.

**Comment by Moon-0xff** [comment]
Don't bother to write a special case if the script is called from inside. `cd "$(dirname "$0")"` updates `$OLDPWD` regardless.

**Comment by Moon-0xff** [comment]
I've run it from nautilus (Right click -> run as program). The terminal window closes itself.
`$SHELL` also opens a shell inside the current one.
The instructions require a terminal already, so we shouldn't worry too much about this.

**Comment by Batwam** [comment]
That's strange as it worked for me. Yeah, I don't normally run scripts from the file browser but I just thought it might be a but more user friendly.

**Comment by Moon-0xff** [comment]
Great. I'm going to merge this now. Thanks again @Batwam

**Pull request merged**
