### PR TITLE
Double click feature

### PR DESCRIPTION
**Pull request by michlampert**
Hi!

Sometimes I felt like I was missing buttons in my mouse (or touchpad) to trigger some options, so I decided to implement double click feature, which work similar to this in portable speakers or headphones.

After changes menu will contain additional options:
- switch to enable/disable double-click feature
- field to configure time interval between successive clicks
- three comboboxes with options for double-clicks next  to single-clicks options

Before:
image

After:
image
image

### CODE REVIEW

**Comment by michlampert** [comment]
Thanks for your feedback @Moon-0xff!

I hope that changes will meet your expectations :smile: 

Photo of menu for reference:
image

**Comment by Moon-0xff** [comment]
> I hope that changes will meet your expectations 😄

Indeed.

Normally I would prefer to avoid the ternary operator but it looks like a good fit here.

The changes to the menu are good.  
For consistency I would underline "Single click" and "Double click" as "Mouse bindings" is underlined.  
I would also  put a blank space between the button bindings and the scroll binding (there's a commented line that produces a blank line somewhere).

**Comment by michlampert** [comment]
image

**Comment by Moon-0xff** [comment]
Great! I don't have more changes to request. Good job!

I will soon inspect the code more closely and perhaps push to this branch, if isn't a problem on your end (is it?).  

After that I will test it a bit and merge it.

**Comment by Moon-0xff** [comment]
I've added some inconsequential (or should be inconsequential) style changes.  
I will add a few more tomorrow.

Let me know if you have any thoughts about, or if there's problems with my commits.  
And don't be afraid of pushing!

**Comment by Moon-0xff** [comment]
I refactored the code to make it easier to understand (I hope).

The logic should be the same.

**Comment by Moon-0xff** [comment]
Alright, I think I'm done now. Please review the changes and if everything looks good to you I will merge it.

One thing to note, I didn't review on detail the `prefs.js` changes, it looks like it behaves like it should and we are thinking of redoing the whole thing (#67).

**Comment by michlampert** [comment]
Looks good to me :wink: 
I'm looking forward to see it in the next release!

**Comment by Moon-0xff** [comment]
Great! I will merge it then.

Thanks again for the PR @michlampert!

**Pull request merged**
