### PR TITLE
update to icon padding mechanism

### PR DESCRIPTION
**Pull request by Batwam**
Hi, minor issue but I noticed that the padding didn't quite work when the icon is on the left. I took the opportunity to rewrite the adjustment to keep things concise as it was basically coding the Max function.

Also, the icon location wasn't loaded properly when opening the Settings so I fixed that too.

### CODE REVIEW

**Comment by Moon-0xff** [comment]
Hello @Batwam, good work catching these problems but have you tried another approach for this? The icon padding hack works well but it's very fiddly, breaks easily and I'm not very comfortable with it.

**Comment by Moon-0xff** [comment]
I have tried to use [Clutter.BoxLayout](https://gjs-docs.gnome.org/clutter11~11_api/clutter.boxlayout) before with no luck.
Now I'm looking at the [GNOME CSS documentation](https://gjs-docs.gnome.org/css/) and perhaps we can set the style in some other, more reliable way.
The interactive example of [border-spacing](https://gjs-docs.gnome.org/css/border-spacing) looks like it does what we want.

**Comment by Batwam** [comment]
Yeah, it's a funny one as it really looks like the padding is applied inconsistently between icons Vs text and gtk3 Vs 4. It would be interesting to see if other method lead to different results. Having looked at the level of padding in other extensions, a few had similar issues with either excessive and/or inconsistent right/left padding. It just looks like most people don't really care. To be honest, it only really noticeable for people with low padding and a bad case of OCD 😄 

I did also consider setting the min padding to 5 which would eliminate the need for the `Max` formula adjustment but it didn't seem worth reducing choice for people using text only just to remove a fraction of a line of code.

**Comment by Moon-0xff** [comment]
Surely there's a way!

**Comment by Moon-0xff** [comment]
I'm still not convinced with this approach, but it works and i can't come up with a better solution so i will merge it.

**Comment by Moon-0xff** [comment]
I reverted the file mode changes. I don't know why they were committed in the first place... I suppose it was a mistake?

**Comment by Batwam** [comment]
Yeah, I was going to look at that as I didn't recognise these changes. No idea how they go committed as they don't reflect the changes I made.

**Comment by Batwam** [comment]
Ok, the changes to pref.js were due to the gap with the current `main`. What was the problem you found with the other commits?

**Comment by Moon-0xff** [comment]
the file mode bits of `extension.js` and `icons.js` were changed from `644` to `755`
this is the same as executing this command:  `chmod +x extension.js icons.js`

If you don't recall something like this maybe you should check your IDE configurations?

**Comment by Batwam** [comment]
ok, that's pretty odd. I have updated the flags for these two files and pushed the update

**Comment by Moon-0xff** [comment]
Don't worry i reverted the file mode already. Thanks for the PR @Batwam

**Comment by Batwam** [comment]
Ok, no worries

**Pull request merged**
