### PR TITLE
Update Controls Preferences Panel

### PR DESCRIPTION
**Pull request by Batwam**
See proposed cosmetic updates to the Preferences panel:
- add `none` option to disable click action
- group backward/forward click with left/middle/right click

image

### CODE REVIEW

**Comment by Batwam** [comment]
Yeah, I don't know. It may sound obvious to us know but I think as especially since these features are somewhat hidden, it probably doesn't hurt to make it as clear as possible.

The word "click" is used for the first left/middle/right. If we change to "button" we should change their description too.

For scroll, we could replace "Mouse scroll" with "Scroll wheel" otherwise?

**Comment by Moon-0xff** [comment]
Well, for me it doesn't trigger a sense of inconsistency, "Mouse click bindings" reads weird, but "Left/Right click" doesn't.  
You can change the first 3 items for consistency if you think it would be better, I don't have an opinion on that.

About the scroll name, it comes from the fact that a mouse wheel isn't the only "thing" that can activate the bindings (same thing with the mouse buttons though, but most peripherals don't have more than two/three buttons), but i don't have a problem with that name.

**Comment by Batwam** [comment]
So the headings would be "Mouse bindings" for buttons and "Scroll bindings" for the wheel? I guess removing "Mouse" makes sense as not everyone will have a mouse, could be trackpad but then shouldn't the first category read "Button bindings"?

**Comment by Moon-0xff** [comment]
Closing this and adding the first commit separately.

**Pull request closed without merging**
