### PR TITLE
Implement mouse thumb bindings

### PR DESCRIPTION
**Pull request by Batwam**
Looks like I can create a pull request from your own changes! Changes look ok, however, on my mouse, 9 is forward and 8 back.

also, don't we need `return Clutter.EVENT_STOP;` each each of the `case 8:`/`case9:`

### CODE REVIEW

**Comment by Batwam** [comment]
Yeah, it's pretty straightforward, probably not worth a full blown branch PR for 2 lines of code (hopefully).

It a bit strange that your buttons might be swapped. I'm judging forward/backward based on the action in the web browser.

I also see from [this page](https://wiki.archlinux.org/title/Mouse_buttons)
> the thumb-tip button is 9, and the inner-thumb button is 8)

**Comment by Moon-0xff** [comment]
They aren't. I didn't test the branch! 😁

**Comment by Moon-0xff** [comment]
I will push the changes then, let me know if something is missing

**Comment by Batwam** [comment]
Yep, fine with me 👍

**Pull request merged**
