### PR TITLE
Update install instructions

### PR DESCRIPTION
**Pull request by Batwam**
as per #6, proposed update to installation instructions

### CODE REVIEW

**Comment by Moon-0xff** [comment]
Let me know what you think.

**Comment by Batwam** [comment]
I wouldn't normally volunteer the testing branch as I assume that those who want it probably know how to get it and those who don't know probably shouldn't use it but I have update the text slightly to make it a bit more fool proof (I think) by having the explainations first.

**Comment by Moon-0xff** [comment]
`main` is the development branch.
`latest-version` is the *stable* branch
I agree `latest-version` is a confusing name.
We should pick a better one. What about `release`? Is that a good name?
`latest-release`?

**Comment by Batwam** [comment]
Ok, that's a bit confusing. I would have thought that the default branch would have been the stable one since it's the one git would clone by default?

I personally think that it would make sense to have `main` for stable branch (the same version which is on `ego`) and `testing` for the development branch one.

**Comment by Moon-0xff** [comment]
Adding `install.sh` retroactively could mess up the commit history. So i will not merge this until v5 is out.

**Pull request merged**
