### PR TITLE
More cleanup for future compatibility

### PR DESCRIPTION
**Pull request by Batwam**
Hello, I noticed a couple more minor changes I'd like to make which apply to the gnome 43/44 version too. It's not 100% necessary to include them in `main` as they can always be part of the gnome45 diff but I though it might be cleaner to merge those first to minimise the differences between the two versions. 

The gnome45 version is now ready to go by the way, I'll publish once this is confirmed.

### CODE REVIEW

**Comment by Moon-0xff** [comment]
I'll wait a bit in case there's something else to add.

Also, please check your email inbox.

**Comment by Batwam** [comment]
Invitation accepted 👍

The commits in this PR were actually already in the previous gnome45 merge request. This is mostly aimed at keeping the gnome 45 PR to the strict minimum but considering the location and nature of the changes, we can certainly keep them within the gnome45 branch/commit/diff.

**Comment by Moon-0xff** [comment]
> Invitation accepted 👍

Thanks!

> The gnome45 port is ready to go so I'm not expecting further changes

Alright, then I'll merge this now. I agree it's better to keep the differences between `main` and the 45 version small.

If the 45 diff is small enough then I think a patch file would be more manageable, though it will require a script and/or some user guidance when installing manually.  
I think it's better than keeping a branch that will inevitably drift from `main`.

**Comment by Batwam** [comment]
@Moon-0xff Sincere apologies as I just noticed a mistake in the last commit due to copy-paste. Could you please update change 'Switch Automatically' with 'Settings' here: https://github.com/Moon-0xff/gnome-mpris-label/pull/83/files#diff-19a9a3efb94bf1b84229bda71ab0ef5badcdbf34ba3a0c9e4152a82c569a21e6R390

**Comment by Moon-0xff** [comment]
Done.

**Pull request merged**
