### PR TITLE
Code cleanup for future compatibility

### PR DESCRIPTION
**Pull request by Batwam**
Hi, I would like to propose some "transparent" updates to the code which don't impact the way it works or looks but will fix some upcoming issues ahead of the transition to gnome 45 based on some the errors I had to fix to get the gnome 45 version.

In the order of the commits, this would be:
- propose to use strict to enforce some "discipline" there
- fix undefined variables (pref.js)
- settings defined as global variable in pref.js
- remove unused dependancies (players.js getIcon() )
- remove unused variables (players.js)
- remove unused function inputs (players.js)
- add schema info to metadata.json
- changes which will become requirements for the gnome45 fork but are transparent for gnome 42 (schema definition, popupMenu Ornament)

The idea would be to merge this and only then introduce the gnome45 PR based on this cleaned up code.

### CODE REVIEW

**Comment by Moon-0xff** [comment]
I would separate 1fe61d4053dacd06bf1fa5e3c735892dc437e3cf and try to merge it first, is almost granted that ego will reject the next version until `settings` is de-globalized.

**Comment by Batwam** [comment]
yep, that's the main one and likely to be a must-have like you said and you can cherry-pick it if you want. However, the other ones are very minor if you want to have a look at them also.

**Comment by Moon-0xff** [comment]
Well, I did.
It also merged c885407f41e6a05f3fc356167ba0962e144e46c7 for some reason, but that's fine.

**Comment by Batwam** [comment]
Ok, that's good. I've synced the branch so there is very little left in term of diff. Feel free to review and merge when you find the time. I can reimplement the gnome45 port and resubmit a cleaned up PR which will hopefully be relatively short too.

**Comment by Batwam** [comment]
ok, those were the main changes. if you look at the diff now, these are minor updates fixing basic/obvious coding errors like undefined variables.

I am now pushing some updates to replace the use of ExtensionUtils as dependancy injection. This was recommended in my chat Just Perfection and will also help limit the code differences between gnome42 and gnome45 versions. Again, no change on the look and feel.

**Comment by Batwam** [comment]
ok I was told to use dependency injection everywhere and avoid Global as much as possible in label.js so I have updated the code accordingly:
image

**Comment by Moon-0xff** [comment]
Looks great, I don't have a problem with merging this as it stands. Though I'm worried `use strict` could silently break stuff.

**Comment by Batwam** [comment]
Yeah, I did notice that with 'use strict', unless the issue is in the main code, it wasn't getting any error, it just fails and I had to go dig to find where the issue came from. It looks like gnome45 will flag these errors or refuse to run anyway so I'm ok if you want to revert that commit.

**Comment by Batwam** [comment]
I guess we should change the variables in label.js to lowercase before merging for consistency but I was running out of time...

**Pull request merged**
